/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_yolosec_upckeygen_algorithms_UpcKeygen */

#ifndef _Included_net_yolosec_upckeygen_algorithms_UpcKeygen
#define _Included_net_yolosec_upckeygen_algorithms_UpcKeygen
#ifdef __cplusplus
extern "C" {
#endif
#undef net_yolosec_upckeygen_algorithms_UpcKeygen_SUPPORTED
#define net_yolosec_upckeygen_algorithms_UpcKeygen_SUPPORTED 2L
#undef net_yolosec_upckeygen_algorithms_UpcKeygen_UNLIKELY_SUPPORTED
#define net_yolosec_upckeygen_algorithms_UpcKeygen_UNLIKELY_SUPPORTED 1L
#undef net_yolosec_upckeygen_algorithms_UpcKeygen_UNSUPPORTED
#define net_yolosec_upckeygen_algorithms_UpcKeygen_UNSUPPORTED 0L
/*
 * Class:     net_yolosec_upckeygen_algorithms_UpcKeygen
 * Method:    upcNative
 * Signature: ([B[BI)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_net_yolosec_upckeygen_algorithms_UpcKeygen_upcNative
        (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
