package net.yolosec.upckeygen.algorithms;

import android.os.Parcel;
import android.os.Parcelable;

/**
 * One WiFi key generated by the generator.
 *
 * Created by dusanklinec on 10.01.16.
 */
public class WiFiKey implements Parcelable {
    public static final int BAND_NA = 0;
    public static final int BAND_24 = 1;
    public static final int BAND_5 = 2;

    private String key;

    /**
     * Estimated serial number of the router.
     */
    private String serial;
    private String ssid;

    /**
     * Frequency range the key was generated for. i.e. for WiFi operating on 2.4 GHz or 5 GHz.
     */
    private int bandType = BAND_NA;

    private int order = 0;

    public WiFiKey() {
    }

    public WiFiKey(String key) {
        this.key = key;
    }

    public WiFiKey(String key, int bandType) {
        this.key = key;
        this.bandType = bandType;
    }

    public WiFiKey(String key, String serial, int bandType) {
        this.key = key;
        this.serial = serial;
        this.bandType = bandType;
    }

    public WiFiKey(String key, String serial, int bandType, int order) {
        this.key = key;
        this.serial = serial;
        this.bandType = bandType;
        this.order = order;
    }

    public String getSsid() {
        return ssid;
    }

    public void setSsid(String ssid) {
        this.ssid = ssid;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public int getBandType() {
        return bandType;
    }

    public void setBandType(int bandType) {
        this.bandType = bandType;
    }

    public String getSerial() {
        return serial;
    }

    public void setSerial(String serial) {
        this.serial = serial;
    }

    public int getOrder() {
        return order;
    }

    public void setOrder(int order) {
        this.order = order;
    }

    @Override
    public String toString() {
        return "WiFiKey{" +
                "key='" + key + '\'' +
                ", serial='" + serial + '\'' +
                ", ssid='" + ssid + '\'' +
                ", bandType=" + bandType +
                ", order=" + order +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        WiFiKey wiFiKey = (WiFiKey) o;

        if (bandType != wiFiKey.bandType) return false;
        if (key != null ? !key.equals(wiFiKey.key) : wiFiKey.key != null) return false;
        if (serial != null ? !serial.equals(wiFiKey.serial) : wiFiKey.serial != null) return false;
        return !(ssid != null ? !ssid.equals(wiFiKey.ssid) : wiFiKey.ssid != null);

    }

    @Override
    public int hashCode() {
        int result = key != null ? key.hashCode() : 0;
        result = 31 * result + (serial != null ? serial.hashCode() : 0);
        result = 31 * result + (ssid != null ? ssid.hashCode() : 0);
        result = 31 * result + bandType;
        return result;
    }

    protected WiFiKey(Parcel in) {
        key = in.readString();
        serial = in.readString();
        bandType = in.readInt();
        order = in.readInt();
        ssid = in.readString();
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(key);
        dest.writeString(serial);
        dest.writeInt(bandType);
        dest.writeInt(order);
        dest.writeString(ssid);
    }

    @SuppressWarnings("unused")
    public static final Parcelable.Creator<WiFiKey> CREATOR = new Parcelable.Creator<WiFiKey>() {
        @Override
        public WiFiKey createFromParcel(Parcel in) {
            return new WiFiKey(in);
        }

        @Override
        public WiFiKey[] newArray(int size) {
            return new WiFiKey[size];
        }
    };
}
